# SPDX-License-Identifier: Apache-2.0

"""Estate health pure types and evaluation (ADR-0017).

Portable open-core surface: no SQLite / FS / launchctl. Collectors live
in :mod:`steward.infra.health`.
"""

from __future__ import annotations

from steward.core.health.evaluate import (
    adapter_run_level,
    age_hours,
    attached_import_level,
    build_health_checks,
    check_broken_audit,
    check_dual_presence_poor,
    check_fp_not_ready,
    check_rollup_stale,
    check_stale_scan,
    check_stash_overdue,
    compute_overall,
    evaluate_fail_on,
    free_space_level,
    latency_level,
    level_for_age,
    parse_iso_to_utc,
    root_scan_level,
    validate_fail_on_tokens,
    worst_level,
)
from steward.core.health.model import (
    AdapterFreshness,
    AdapterRunHealth,
    AttachedImportHealth,
    DualPresenceSection,
    EstateHealthReport,
    FleetHealthSummary,
    FPSection,
    HealthCheckName,
    HealthCheckResult,
    HealthLevel,
    HealthRollupInfo,
    InventoryIntegrity,
    MountProbe,
    RootScanFreshness,
    ScheduleHealth,
    ScheduleTemplateHealth,
    StashHealth,
)
from steward.core.health.thresholds import (
    DEFAULT_CHECK_FAIL_ON,
    DEFAULT_THRESHOLDS,
    FAIL_ON_ATTACHED_MISSING,
    FAIL_ON_BROKEN_AUDIT,
    FAIL_ON_DUAL_PRESENCE_POOR,
    FAIL_ON_ENVELOPE_SLA,
    FAIL_ON_FLEET_CHAIN_STALE,
    FAIL_ON_FLEET_STALE_SCAN,
    FAIL_ON_FP_NOT_READY,
    FAIL_ON_ROLLUP_STALE,
    FAIL_ON_STALE_SCAN,
    FAIL_ON_STASH_OVERDUE,
    KNOWN_FAIL_ON_TOKENS,
    HealthThresholds,
)

__all__ = [
    "DEFAULT_CHECK_FAIL_ON",
    "DEFAULT_THRESHOLDS",
    "FAIL_ON_BROKEN_AUDIT",
    "FAIL_ON_DUAL_PRESENCE_POOR",
    "FAIL_ON_FLEET_STALE_SCAN",
    "FAIL_ON_FLEET_CHAIN_STALE",
    "FAIL_ON_ENVELOPE_SLA",
    "FAIL_ON_ATTACHED_MISSING",
    "FAIL_ON_FP_NOT_READY",
    "FAIL_ON_ROLLUP_STALE",
    "FAIL_ON_STALE_SCAN",
    "FAIL_ON_STASH_OVERDUE",
    "KNOWN_FAIL_ON_TOKENS",
    "AdapterFreshness",
    "AdapterRunHealth",
    "AttachedImportHealth",
    "DualPresenceSection",
    "EstateHealthReport",
    "FleetHealthSummary",
    "FPSection",
    "HealthCheckName",
    "HealthCheckResult",
    "HealthLevel",
    "HealthRollupInfo",
    "HealthThresholds",
    "InventoryIntegrity",
    "MountProbe",
    "RootScanFreshness",
    "ScheduleHealth",
    "ScheduleTemplateHealth",
    "StashHealth",
    "age_hours",
    "adapter_run_level",
    "attached_import_level",
    "build_health_checks",
    "check_broken_audit",
    "check_dual_presence_poor",
    "check_fp_not_ready",
    "check_rollup_stale",
    "check_stale_scan",
    "check_stash_overdue",
    "compute_overall",
    "evaluate_fail_on",
    "free_space_level",
    "latency_level",
    "level_for_age",
    "parse_iso_to_utc",
    "root_scan_level",
    "validate_fail_on_tokens",
    "worst_level",
]
